export const VILLAGE_OPTIONS = [
  { value: "ખાંભડા", label: "ખાંભડા" },
  { value: "દૂધાળા", label: "દૂધાળા" },
  { value: "તાજપર", label: "તાજપર" },
  { value: "લીમડા", label: "લીમડા" },
  { value: "ઉન્ટવડ", label: "ઉન્ટવડ" },
  { value: "ઘૂઘરાળા", label: "ઘૂઘરાળા" },
  { value: "જલાલપર", label: "જલાલપર" },
  { value: "તરઘરા", label: "તરઘરા" },
  { value: "ચમારડી", label: "ચમારડી" },
  { value: "બાબરા", label: "બાબરા" },
  { value: "લાઠી", label: "લાઠી" },
  { value: "રણછોડપુર", label: "રણછોડપુર" },
  { value: "ખાખરીયા", label: "ખાખરીયા" },
  { value: "માંડવી", label: "માંડવી" },
  { value: "રામપર", label: "રામપર" },
  { value: "દામનગર", label: "દામનગર" },
  { value: "પ્રતાપગઢ", label: "પ્રતાપગઢ" },
  { value: "ઠાંસા", label: "ઠાંસા" },
  { value: "ખીજડીયા", label: "ખીજડીયા" },
  { value: "રાજુલા", label: "રાજુલા" },
  { value: "ઉમરડા", label: "ઉમરડા" },
  { value: "આટકોટ", label: "આટકોટ" },
  { value: "મૂળિયાપટ", label: "મૂળિયાપટ" },
];
